import { Ionicons } from '@expo/vector-icons'
import { router } from 'expo-router'
import { useMemo, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native'
import { useKashFlow } from '../../src/components/KashFlowProvider'

type Filter = 'all' | 'pending' | 'review' | 'synced'
const filters: { key: Filter; label: string }[] = [{ key: 'all', label: 'All activity' }, { key: 'pending', label: 'To sync' }, { key: 'review', label: 'Review' }, { key: 'synced', label: 'Synced' }]

export default function SyncScreen() {
  const { online, syncing, snapshot, syncNow, refresh } = useKashFlow()
  const [filter, setFilter] = useState<Filter>('all')
  const counts = useMemo(() => snapshot?.counts ?? [], [snapshot?.counts])
  const pending = counts.filter((count) => count.state === 'pending').length
  const conflicts = counts.filter((count) => count.state === 'conflict').length
  const synced = counts.filter((count) => count.state === 'synced').length
  const visibleCounts = useMemo(() => counts.filter((count) => {
    if (filter === 'pending') return count.state === 'pending'
    if (filter === 'review') return count.state === 'conflict'
    if (filter === 'synced') return count.state === 'synced' || count.state === 'superseded'
    return true
  }), [counts, filter])

  return <View style={styles.screen}><ScrollView contentContainerStyle={styles.page} showsVerticalScrollIndicator={false}>
    <View style={styles.head}><View><Text style={styles.kicker}>DEVICE ACTIVITY</Text><Text style={styles.title}>Sync & review</Text></View><View style={[styles.network, online ? styles.networkOnline : styles.networkOffline]}><View style={[styles.networkDot, online ? styles.dotOnline : styles.dotOffline]} /><Text style={[styles.networkText, online ? styles.textOnline : styles.textOffline]}>{online ? 'CONNECTED' : 'OFFLINE'}</Text></View></View>
    <Text style={styles.subtitle}>Everything you count is saved here first, then checked against the live stock balance.</Text>

    <View style={styles.summary}><View style={styles.summaryCell}><Text style={[styles.summaryNumber, pending > 0 && styles.pendingNumber]}>{pending}</Text><Text style={styles.summaryLabel}>TO SYNC</Text></View><View style={styles.rule} /><View style={styles.summaryCell}><Text style={[styles.summaryNumber, conflicts > 0 && styles.conflictNumber]}>{conflicts}</Text><Text style={styles.summaryLabel}>REVIEW</Text></View><View style={styles.rule} /><View style={styles.summaryCell}><Text style={styles.summaryNumber}>{synced}</Text><Text style={styles.summaryLabel}>SYNCED</Text></View></View>

    <View style={styles.syncBanner}><View style={styles.bannerIcon}><Ionicons name={online ? 'cloud-upload-outline' : 'cloud-offline-outline'} size={20} color={online ? '#147e68' : '#a97834'} /></View><View style={styles.bannerCopy}><Text style={styles.bannerTitle}>{online ? 'Ready when you are' : 'Your counts are safe here'}</Text><Text style={styles.bannerText}>{online ? 'We’ll verify each baseline before adjusting stock.' : 'Reconnect to send counts and check for changes at the business.'}</Text></View><Pressable disabled={!online || syncing || pending === 0} onPress={() => void syncNow()} style={[styles.syncButton, (!online || pending === 0 || syncing) && styles.syncDisabled]}>{syncing ? <ActivityIndicator size="small" color="#fff" /> : <Ionicons name="sync-outline" size={15} color="#fff" />}<Text style={styles.syncButtonText}>{syncing ? 'Working' : 'Sync now'}</Text></Pressable></View>

    <ScrollView horizontal showsHorizontalScrollIndicator={false} contentContainerStyle={styles.filters}>{filters.map((item) => <Pressable key={item.key} onPress={() => setFilter(item.key)} style={[styles.filter, filter === item.key && styles.filterActive]}><Text style={[styles.filterText, filter === item.key && styles.filterTextActive]}>{item.label}{item.key === 'pending' && pending > 0 ? ` · ${pending}` : item.key === 'review' && conflicts > 0 ? ` · ${conflicts}` : ''}</Text></Pressable>)}</ScrollView>

    <Text style={styles.listLabel}>{filter === 'all' ? 'RECENT ACTIVITY' : filters.find((item) => item.key === filter)?.label.toUpperCase()}</Text>
    <View style={styles.list}>
      {visibleCounts.map((count) => <View key={count.idempotencyKey} style={[styles.countCard, count.state === 'conflict' && styles.conflictCard]}>
        <View style={[styles.countIcon, count.state === 'conflict' ? styles.iconConflict : count.state === 'synced' || count.state === 'superseded' ? styles.iconSynced : styles.iconPending]}><Ionicons name={count.state === 'conflict' ? 'alert-outline' : count.state === 'synced' || count.state === 'superseded' ? 'checkmark' : 'time-outline'} size={17} color={count.state === 'conflict' ? '#b17831' : count.state === 'synced' || count.state === 'superseded' ? '#12856a' : '#5d7884'} /></View>
        <View style={styles.countBody}><View style={styles.countTop}><Text numberOfLines={1} style={styles.itemName}>{count.itemName}</Text><Text style={styles.counted}>{count.countedQuantity.toLocaleString(undefined, { maximumFractionDigits: 3 })}</Text></View><Text style={styles.countMeta}>{count.locationName} · baseline {count.expectedQuantity.toLocaleString(undefined, { maximumFractionDigits: 3 })} · {new Date(count.createdAt).toLocaleDateString()}</Text>
          {count.state === 'conflict' && <><View style={styles.conflictFacts}><Text style={styles.fact}>At count start <Text style={styles.factValue}>{count.expectedQuantity}</Text></Text><Text style={styles.fact}>Current in business <Text style={styles.factValue}>{count.serverQuantity ?? '—'}</Text></Text></View><Text style={styles.conflictMessage}>{count.message || 'Stock changed after the count began.'}</Text><Pressable onPress={() => router.push(`/(tabs)/count?itemId=${encodeURIComponent(count.itemId)}&locationId=${encodeURIComponent(count.locationId)}&supersedes=${encodeURIComponent(count.idempotencyKey)}`)} disabled={!online} style={[styles.resolveButton, !online && styles.resolveDisabled]}><Ionicons name="refresh-outline" size={14} color="#9d692a" /><Text style={styles.resolveText}>{online ? 'Recount this location' : 'Reconnect to review'}</Text></Pressable></>}
          {count.state === 'pending' && <Text style={styles.pendingCaption}>{online ? 'Waiting to sync · baseline check will run first' : 'Saved on this device · will sync when connected'}</Text>}
          {count.state === 'synced' && <Text style={styles.syncedCaption}>Posted to inventory and checked against the saved baseline.</Text>}
          {count.state === 'superseded' && <Text style={styles.supersededCaption}>Recounted after a stock change. The newer count is in the queue.</Text>}
        </View>
      </View>)}
      {visibleCounts.length === 0 && <View style={styles.empty}><View style={styles.emptyIcon}><Ionicons name={filter === 'review' ? 'checkmark-done-outline' : 'file-tray-outline'} size={21} color="#18876d" /></View><Text style={styles.emptyTitle}>{filter === 'review' ? 'You’re all caught up' : filter === 'pending' ? 'No counts waiting to sync' : 'Nothing here yet'}</Text><Text style={styles.emptyText}>{filter === 'review' ? 'Any count that finds a changed balance will appear here for you to review.' : 'Start a physical count and your activity will appear here.'}</Text></View>}
    </View>
    {online && <Pressable onPress={() => void refresh()} style={styles.refresh}><Ionicons name="refresh-outline" size={14} color="#4f766c" /><Text style={styles.refreshText}>Refresh live inventory</Text></Pressable>}
    <View style={styles.note}><Ionicons name="shield-checkmark-outline" size={14} color="#738d82" /><Text style={styles.noteText}>Retrying a count is safe: each saved count can only create one stock adjustment.</Text></View>
  </ScrollView></View>
}

const styles = StyleSheet.create({
  screen: { flex: 1, backgroundColor: '#f6f5f1' }, page: { paddingHorizontal: 20, paddingTop: 22, paddingBottom: 28, maxWidth: 650, width: '100%', alignSelf: 'center' },
  head: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' }, kicker: { color: '#128b70', fontSize: 11, fontWeight: '900', letterSpacing: 1.5 }, title: { color: '#19272d', fontSize: 24, fontWeight: '800', letterSpacing: -0.8, marginTop: 4 }, subtitle: { color: '#85918b', fontSize: 13, lineHeight: 15, marginTop: 6 },
  network: { height: 27, borderRadius: 15, paddingHorizontal: 9, flexDirection: 'row', alignItems: 'center', gap: 6 }, networkOnline: { backgroundColor: '#e4f2eb' }, networkOffline: { backgroundColor: '#fff1db' }, networkDot: { width: 6, height: 6, borderRadius: 4 }, dotOnline: { backgroundColor: '#1a9f79' }, dotOffline: { backgroundColor: '#bb8035' }, networkText: { fontSize: 10, fontWeight: '900', letterSpacing: 0.9 }, textOnline: { color: '#167f66' }, textOffline: { color: '#a67531' },
  summary: { marginTop: 17, minHeight: 75, borderRadius: 16, borderWidth: 1, borderColor: '#e7e9e3', backgroundColor: '#fff', flexDirection: 'row', alignItems: 'center', paddingHorizontal: 14 }, summaryCell: { flex: 1 }, summaryNumber: { color: '#243438', fontSize: 18, fontWeight: '800' }, pendingNumber: { color: '#b07831' }, conflictNumber: { color: '#ad6038' }, summaryLabel: { color: '#929d97', fontSize: 10, fontWeight: '900', letterSpacing: 1.2, marginTop: 3 }, rule: { height: 31, width: 1, backgroundColor: '#eceee8', marginHorizontal: 12 },
  syncBanner: { marginTop: 11, backgroundColor: '#eaf4ee', borderColor: '#dcebe2', borderWidth: 1, borderRadius: 15, padding: 12, flexDirection: 'row', alignItems: 'center', gap: 9 }, bannerIcon: { width: 35, height: 35, borderRadius: 12, backgroundColor: '#d9ede2', alignItems: 'center', justifyContent: 'center' }, bannerCopy: { flex: 1 }, bannerTitle: { color: '#27443c', fontSize: 13, fontWeight: '800' }, bannerText: { color: '#71827b', fontSize: 11, lineHeight: 12, marginTop: 3 }, syncButton: { height: 34, paddingHorizontal: 9, borderRadius: 10, backgroundColor: '#138b70', flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 5 }, syncDisabled: { backgroundColor: '#a9bbb1' }, syncButtonText: { color: '#fff', fontSize: 11, fontWeight: '900' },
  filters: { gap: 7, marginTop: 17, paddingRight: 14 }, filter: { height: 32, borderRadius: 11, backgroundColor: '#e9ece6', paddingHorizontal: 12, justifyContent: 'center' }, filterActive: { backgroundColor: '#15353a' }, filterText: { color: '#67756f', fontSize: 11, fontWeight: '800' }, filterTextActive: { color: '#fff' }, listLabel: { color: '#949f99', fontSize: 10, fontWeight: '900', letterSpacing: 1.4, marginTop: 20, marginBottom: 8 }, list: { gap: 8 },
  countCard: { backgroundColor: '#fff', borderColor: '#e8eae4', borderWidth: 1, borderRadius: 15, padding: 11, flexDirection: 'row', alignItems: 'flex-start', gap: 9 }, conflictCard: { backgroundColor: '#fffaf2', borderColor: '#efdfc5' }, countIcon: { width: 31, height: 31, borderRadius: 11, alignItems: 'center', justifyContent: 'center' }, iconConflict: { backgroundColor: '#fff0d5' }, iconSynced: { backgroundColor: '#e6f3eb' }, iconPending: { backgroundColor: '#edf2f3' }, countBody: { flex: 1 }, countTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 6 }, itemName: { color: '#26373a', fontSize: 13, fontWeight: '800', flex: 1 }, counted: { color: '#25383a', fontSize: 12, fontWeight: '800' }, countMeta: { color: '#8d9892', fontSize: 11, marginTop: 4 },
  conflictFacts: { flexDirection: 'row', gap: 8, flexWrap: 'wrap', marginTop: 10 }, fact: { backgroundColor: '#fff', borderRadius: 8, borderWidth: 1, borderColor: '#f1e4ce', paddingHorizontal: 8, paddingVertical: 5, color: '#997c50', fontSize: 10 }, factValue: { color: '#624b2d', fontWeight: '900' }, conflictMessage: { color: '#947749', fontSize: 11, lineHeight: 13, marginTop: 8 }, resolveButton: { alignSelf: 'flex-start', marginTop: 10, paddingHorizontal: 10, height: 31, borderWidth: 1, borderColor: '#e8d5b4', backgroundColor: '#fff5e4', borderRadius: 9, flexDirection: 'row', alignItems: 'center', gap: 5 }, resolveDisabled: { opacity: 0.6 }, resolveText: { color: '#966627', fontSize: 11, fontWeight: '900' }, pendingCaption: { color: '#80908a', fontSize: 11, marginTop: 7 }, syncedCaption: { color: '#678c7b', fontSize: 11, marginTop: 7 }, supersededCaption: { color: '#919992', fontSize: 11, marginTop: 7 },
  empty: { alignItems: 'center', paddingVertical: 25, paddingHorizontal: 20, backgroundColor: '#fff', borderRadius: 15, borderWidth: 1, borderColor: '#e7e9e3' }, emptyIcon: { width: 39, height: 39, borderRadius: 13, backgroundColor: '#e8f4ed', alignItems: 'center', justifyContent: 'center' }, emptyTitle: { color: '#293a3b', fontSize: 14, fontWeight: '800', marginTop: 9 }, emptyText: { color: '#89948e', fontSize: 11, lineHeight: 13, textAlign: 'center', marginTop: 4, maxWidth: 240 },
  refresh: { flexDirection: 'row', alignSelf: 'center', alignItems: 'center', gap: 6, paddingVertical: 11 }, refreshText: { color: '#577b6e', fontSize: 11, fontWeight: '800' }, note: { flexDirection: 'row', justifyContent: 'center', alignItems: 'flex-start', gap: 6, marginTop: 3 }, noteText: { maxWidth: 265, textAlign: 'center', color: '#89958f', fontSize: 11, lineHeight: 13 },
})
