import { useMemo, useState } from 'react'
import {
  Activity, ArrowDownLeft, ArrowRight, ArrowUpRight, Bell, BookOpen, BriefcaseBusiness,
  Building2, CalendarDays, Check, ChevronDown, ChevronRight, CircleHelp, CreditCard,
  FileCheck2, FileClock, FileText, Filter, Gauge, HandCoins, Landmark,
  LayoutDashboard, LifeBuoy, Menu, MoreHorizontal, Package, Plus, Search,
  Settings2, ShieldCheck, ShoppingBag, Sparkles, Users, Wallet, X,
} from 'lucide-react'
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis } from 'recharts'
import './App.css'

const groups = [
  { title: 'WORKSPACE', items: [['Overview', LayoutDashboard], ['Banking', Landmark], ['Sales', ArrowUpRight], ['Expenses', ArrowDownLeft], ['Payroll', Users]] },
  { title: 'MANAGE', items: [['Customers', Users], ['Suppliers', ShoppingBag], ['Inventory', Package], ['Projects', BriefcaseBusiness], ['Accounting', BookOpen]] },
  { title: 'INSIGHTS & COMPLIANCE', items: [['Reports', Activity], ['Kenya compliance', ShieldCheck], ['Documents', FileText]] },
] as const
const activity = [
  { initials: 'KM', name: 'Kifaru Media Ltd', detail: 'Invoice #INV-2048 · M-Pesa', date: 'Today, 10:42 AM', amount: '+ KSh 84,500', status: 'Received', color: 'lavender' },
  { initials: 'S', name: 'Safaricom PLC', detail: 'Internet & airtime · M-Pesa', date: 'Today, 9:18 AM', amount: '− KSh 12,300', status: 'Categorized', color: 'mint' },
  { initials: 'AC', name: 'Amani Creative Studio', detail: 'Invoice #INV-2045 · Bank transfer', date: 'Yesterday', amount: '+ KSh 126,000', status: 'Received', color: 'peach' },
  { initials: 'TN', name: 'Tawi Networks', detail: 'Cloud services · KCB Bank', date: 'Yesterday', amount: '− KSh 8,750', status: 'Review', color: 'blue' },
]
const compliance = [
  { name: 'KRA eTIMS', detail: 'Sales invoices · synced today', status: 'Connected', tone: 'green', icon: FileCheck2 },
  { name: 'PAYE & SHIF', detail: 'September payroll · due 9 Oct', status: 'Ready to file', tone: 'blue', icon: Users },
  { name: 'NSSF', detail: 'September contributions · due 9 Oct', status: 'Ready to file', tone: 'blue', icon: Landmark },
  { name: 'Affordable Housing Levy', detail: 'September return · due 9 Oct', status: 'Review needed', tone: 'amber', icon: Building2 },
]
const chart = [
  { date: 'Sep 01', income: 245, expense: 145 }, { date: 'Sep 05', income: 360, expense: 225 },
  { date: 'Sep 09', income: 295, expense: 190 }, { date: 'Sep 13', income: 490, expense: 285 },
  { date: 'Sep 17', income: 410, expense: 240 }, { date: 'Sep 21', income: 560, expense: 330 },
  { date: 'Sep 25', income: 475, expense: 275 }, { date: 'Sep 29', income: 680, expense: 390 },
]
const descriptions: Record<string, string> = {
  Banking: 'Connect accounts, reconcile transactions, and manage cash flow.', Sales: 'Create invoices, track payments, and manage customer quotes.',
  Expenses: 'Capture bills, categorize spend, and manage reimbursements.', Payroll: 'Run payroll and prepare statutory deductions for your team.',
  Customers: 'Manage customer contacts, balances, and payment history.', Suppliers: 'Manage vendor bills, payment terms, and supplier records.',
  Inventory: 'Track stock levels, purchase orders, and product costs.', Projects: 'Monitor project budgets, time, and profitability.',
  Accounting: 'Review your chart of accounts, journal entries, and reconciliations.', Reports: 'Explore financial statements and customizable business reports.',
  'Kenya compliance': 'Review local tax registrations, filings, and statutory payroll.', Documents: 'Store receipts, contracts, tax files, and business records.',
}

function App() {
  const [page, setPage] = useState('Overview')
  const [period, setPeriod] = useState('This month')
  const [search, setSearch] = useState('')
  const [modal, setModal] = useState<'invoice' | 'transaction' | null>(null)
  const [toast, setToast] = useState('')
  const [sidebarOpen, setSidebarOpen] = useState(false)
  const [notifications, setNotifications] = useState(false)
  const [invoiceCount, setInvoiceCount] = useState(12)
  const filtered = useMemo(() => activity.filter((row) => `${row.name} ${row.detail} ${row.status}`.toLowerCase().includes(search.toLowerCase())), [search])
  function notify(message: string) { setToast(message); window.setTimeout(() => setToast(''), 2800) }
  function saveInvoice() { setInvoiceCount((count) => count + 1); setModal(null); notify('Draft invoice created successfully') }

  return <div className="app-shell">
    <aside className={`sidebar ${sidebarOpen ? 'sidebar-open' : ''}`}>
      <div className="brand-row"><div className="brand-mark">K</div><div className="brand-name">Kash<span>Flow</span><small>BUSINESS SUITE</small></div><button className="icon-button sidebar-close" onClick={() => setSidebarOpen(false)} aria-label="Close menu"><X size={18} /></button></div>
      <button className="company-switcher" onClick={() => notify('Company switcher is ready to connect')}><span className="company-avatar">A</span><span className="company-copy"><strong>Acme Studio Ltd</strong><small>Business plan</small></span><ChevronDown size={15} /></button>
      <nav className="side-nav" aria-label="Main navigation">{groups.map((group) => <div className="nav-group" key={group.title}><p className="nav-heading">{group.title}</p>{group.items.map(([name, Icon]) => <button key={name} className={`nav-link ${page === name ? 'active' : ''}`} onClick={() => { setPage(name); setSidebarOpen(false) }}><Icon size={18} strokeWidth={1.8} /><span>{name}</span>{(name === 'Banking' || name === 'Kenya compliance') && <span className={`nav-badge ${name === 'Kenya compliance' ? 'amber' : ''}`}>{name === 'Banking' ? '3' : '2'}</span>}</button>)}</div>)}</nav>
      <div className="sidebar-bottom"><div className="help-card"><div className="help-icon"><Sparkles size={16} /></div><strong>Meet KashFlow AI</strong><p>Your books, understood. Ask anything.</p><button onClick={() => notify('KashFlow AI assistant is coming soon')}>Explore assistant <ArrowRight size={14} /></button></div><button className="nav-link bottom-link" onClick={() => notify('Settings opened')}><Settings2 size={18} /> Settings</button><button className="nav-link bottom-link" onClick={() => notify('Help centre opened')}><LifeBuoy size={18} /> Help & support</button><div className="profile-row"><div className="profile-avatar">JN</div><div className="profile-copy"><strong>Joyce Njeri</strong><small>Admin · Acme Studio</small></div><MoreHorizontal size={18} /></div></div>
    </aside>

    <main className="main-area"><header className="topbar"><button className="icon-button mobile-menu" aria-label="Open menu" onClick={() => setSidebarOpen(true)}><Menu size={20} /></button><div className="breadcrumbs"><span>Acme Studio Ltd</span><ChevronRight size={14} /><strong>{page}</strong></div><div className="topbar-actions"><label className="search-box"><Search size={16} /><input aria-label="Search transactions" placeholder="Search anything..." value={search} onChange={(event) => setSearch(event.target.value)} /><kbd>⌘ K</kbd></label><button className="icon-button notification-button" aria-label="Notifications" onClick={() => setNotifications((visible) => !visible)}><Bell size={18} /><i /></button><button className="top-help" onClick={() => notify('Help centre opened')}><CircleHelp size={17} /><span>Help</span></button></div>{notifications && <div className="notification-popover"><strong>You're all caught up</strong><p>We'll let you know when something needs your attention.</p><button onClick={() => setNotifications(false)}>Close</button></div>}</header>
      <div className="content-wrap">{page === 'Overview' ? <>
        <section className="welcome-row"><div><div className="eyebrow"><span className="live-dot" /> YOUR BUSINESS AT A GLANCE</div><h1>Good morning, Joyce <span>✳</span></h1><p className="welcome-subtitle">Here’s what’s happening with Acme Studio today.</p></div><div className="welcome-actions"><button className="button button-secondary" onClick={() => setModal('transaction')}><Plus size={16} /> Add transaction</button><button className="button button-primary" onClick={() => setModal('invoice')}><Plus size={17} /> Create invoice</button></div></section>
        <section className="metric-grid" aria-label="Business summary">
          {[
            { title: 'Total cash', value: 'KSh 2,485,320', rate: '12.8%', Icon: Wallet, tone: 'mint-icon', bars: '' },
            { title: 'Income', value: 'KSh 842,500', rate: '8.2%', Icon: ArrowDownLeft, tone: 'purple-icon', bars: 'purple-bars' },
            { title: 'Expenses', value: 'KSh 326,840', rate: '3.1%', Icon: ArrowUpRight, tone: 'peach-icon', bars: 'orange-bars' },
            { title: 'Profit', value: 'KSh 515,660', rate: '15.4%', Icon: Gauge, tone: 'blue-icon', bars: 'blue-bars' },
          ].map(({ title, value, rate, Icon, tone, bars }) => <article className="metric-card" key={title}><div className="metric-top"><span>{title}</span><span className={`metric-icon ${tone}`}><Icon size={17} /></span></div><div className="metric-value">{value}</div><div className="metric-foot"><span className={`trend ${title === 'Expenses' ? 'negative' : 'positive'}`}><ArrowUpRight size={14} /> {rate}</span><span>vs. last month</span><div className={`mini-bars ${bars}`}>{[42, 62, 48, 77, 56, 88, 68, 100].map((height, i) => <i key={i} style={{ height: `${height}%` }} />)}</div></div></article>)}
        </section>
        <section className="dashboard-grid"><article className="panel cashflow-panel"><div className="panel-header"><div><h2>Cash flow</h2><p>Track money in and out of your business</p></div><button className="period-select" onClick={() => setPeriod(period === 'This month' ? 'Last month' : 'This month')}><CalendarDays size={14} /> {period} <ChevronDown size={14} /></button></div><div className="chart-legend"><span><i className="legend-income" /> Income <strong>KSh 842.5k</strong></span><span><i className="legend-expense" /> Expenses <strong>KSh 326.8k</strong></span></div><div className="chart-wrap"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart} margin={{ top: 10, right: 5, left: -24, bottom: 0 }}><defs><linearGradient id="incomeFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#7256df" stopOpacity={0.17} /><stop offset="100%" stopColor="#7256df" stopOpacity={0} /></linearGradient><linearGradient id="expenseFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#38b99a" stopOpacity={0.13} /><stop offset="100%" stopColor="#38b99a" stopOpacity={0} /></linearGradient></defs><CartesianGrid vertical={false} stroke="#eff0f4" strokeDasharray="4 5" /><XAxis dataKey="date" axisLine={false} tickLine={false} tick={{ fill: '#9699a5', fontSize: 10 }} dy={9} /><Tooltip formatter={(value) => [`KSh ${Number(value).toLocaleString()}k`, '']} contentStyle={{ border: '1px solid #eeedf2', borderRadius: 10, fontSize: 12 }} /><Area type="monotone" dataKey="income" stroke="#7256df" strokeWidth={2.5} fill="url(#incomeFill)" /><Area type="monotone" dataKey="expense" stroke="#48b99e" strokeWidth={2.5} fill="url(#expenseFill)" /></AreaChart></ResponsiveContainer></div><div className="chart-footer"><span><span className="status-dot" /> Looking healthy</span><button onClick={() => setPage('Reports')}>View cash flow report <ArrowRight size={14} /></button></div></article>
          <article className="panel compliance-panel"><div className="panel-header"><div><h2>Kenya compliance</h2><p>Stay on top of local obligations</p></div><button className="icon-button more-button" aria-label="Compliance options" onClick={() => setPage('Kenya compliance')}><MoreHorizontal size={19} /></button></div><div className="due-banner"><div className="due-icon"><CalendarDays size={17} /></div><div><strong>Next filing due in 7 days</strong><span>September payroll returns · 9 October 2026</span></div><ChevronRight size={16} /></div><div className="compliance-list">{compliance.map(({ name, detail, icon: Icon, status, tone }) => <button className="compliance-item" key={name} onClick={() => setPage('Kenya compliance')}><span className={`compliance-icon ${tone}`}><Icon size={16} /></span><span className="compliance-copy"><strong>{name}</strong><small>{detail}</small></span><span className={`status-pill ${tone}`}>{status}</span></button>)}</div><button className="text-link compliance-link" onClick={() => setPage('Kenya compliance')}>View compliance centre <ArrowRight size={14} /></button></article></section>
        <section className="bottom-grid"><article className="panel transactions-panel"><div className="panel-header"><div><h2>Recent transactions</h2><p>Your latest business activity</p></div><button className="button button-small" onClick={() => setPage('Banking')}>View all <ArrowRight size={14} /></button></div><div className="table-tools"><span>{search ? `Results for “${search}”` : 'Showing latest activity'}</span><button onClick={() => notify('Filters are ready to configure')}><Filter size={14} /> Filter</button></div><div className="transaction-table"><div className="table-head"><span>DESCRIPTION</span><span>DATE</span><span>AMOUNT</span><span>STATUS</span></div>{filtered.map((item) => <div className="transaction-row" key={item.name}><div className="transaction-name"><span className={`merchant-avatar ${item.color}`}>{item.initials}</span><span><strong>{item.name}</strong><small>{item.detail}</small></span></div><span className="transaction-date">{item.date}</span><strong className={`transaction-amount ${item.amount.startsWith('+') ? 'amount-in' : ''}`}>{item.amount}</strong><span className={`transaction-status ${item.status === 'Review' ? 'needs-review' : ''}`}><i />{item.status}</span></div>)}{filtered.length === 0 && <div className="empty-state">No matching transactions. Try another search.</div>}</div></article>
          <article className="panel tasks-panel"><div className="panel-header"><div><h2>On your radar</h2><p>A few things need your attention</p></div><span className="task-count">3</span></div><button className="task-item" onClick={() => setPage('Sales')}><span className="task-symbol task-purple"><FileClock size={16} /></span><span className="task-copy"><strong>Invoices awaiting payment</strong><small>{invoiceCount} invoices · KSh 214,300</small></span><span className="task-arrow"><ArrowRight size={14} /></span></button><button className="task-item" onClick={() => setPage('Banking')}><span className="task-symbol task-orange"><CreditCard size={16} /></span><span className="task-copy"><strong>Transactions to review</strong><small>3 bank transactions need matching</small></span><span className="task-arrow"><ArrowRight size={14} /></span></button><button className="task-item" onClick={() => setPage('Kenya compliance')}><span className="task-symbol task-blue"><HandCoins size={16} /></span><span className="task-copy"><strong>Payroll filing coming up</strong><small>PAYE, SHIF & NSSF · due 9 Jun</small></span><span className="task-arrow"><ArrowRight size={14} /></span></button><button className="task-footer" onClick={() => setPage('Kenya compliance')}>See all tasks <ArrowRight size={14} /></button></article></section>
        <footer className="page-footer"><span>© 2026 KashFlow Technologies</span><span><i className="secure-dot" /> All systems operational</span><button onClick={() => notify('Help centre opened')}>Need help?</button></footer>
      </> : <section className="module-page"><div className="eyebrow"><span className="live-dot" /> KASHFLOW WORKSPACE</div><h1>{page}</h1><p className="welcome-subtitle">{descriptions[page] ?? 'Manage your business from one connected workspace.'}</p><div className="module-card"><div className="module-icon"><ShieldCheck size={23} /></div><h2>{page === 'Kenya compliance' ? 'Kenya-ready compliance, all in one place' : `Your ${page.toLowerCase()} workspace`}</h2><p>{page === 'Kenya compliance' ? 'Prepare and track KRA eTIMS, VAT, PAYE, SHIF, NSSF, and Affordable Housing Levy obligations. Live filing requires authorized provider connections.' : 'This workspace is ready to grow with your business. Connect your accounts and configure your workflow to get started.'}</p><div className="module-actions"><button className="button button-primary" onClick={() => page === 'Kenya compliance' ? notify('Compliance setup started') : setModal('transaction')}><Plus size={16} /> {page === 'Kenya compliance' ? 'Set up compliance' : `Add ${page === 'Banking' ? 'account' : page === 'Sales' ? 'invoice' : 'new item'}`}</button><button className="button button-secondary" onClick={() => setPage('Overview')}>Back to overview</button></div></div><div className="module-footnote"><ShieldCheck size={16} /> Demo workspace with sample business data. No government, bank, or mobile-money services are connected.</div></section>}</div>
    </main>

    {modal && <div className="modal-backdrop" role="presentation" onClick={(event) => { if (event.target === event.currentTarget) setModal(null) }}><div className="dialog" role="dialog" aria-modal="true" aria-labelledby="dialog-title"><div className="dialog-head"><div><div className="eyebrow">ACME STUDIO LTD</div><h2 id="dialog-title">{modal === 'invoice' ? 'Create an invoice' : 'Add a transaction'}</h2></div><button className="icon-button" aria-label="Close dialog" onClick={() => setModal(null)}><X size={19} /></button></div>{modal === 'invoice' ? <><label className="field-label">Customer<input placeholder="Search or add a customer" /></label><div className="field-row"><label className="field-label">Invoice date<input type="date" defaultValue="2026-10-02" /></label><label className="field-label">Due date<input type="date" defaultValue="2026-10-09" /></label></div><label className="field-label">Description<input placeholder="What are you charging for?" /></label><div className="field-row"><label className="field-label">Amount (KSh)<input type="number" placeholder="0.00" /></label><label className="field-label">VAT rate<select defaultValue="16%"><option>16%</option><option>0%</option><option>Exempt</option></select></label></div><div className="dialog-note"><Check size={15} /> KRA eTIMS invoice details can be added after connecting an authorized service.</div><div className="dialog-actions"><button className="button button-secondary" onClick={() => setModal(null)}>Cancel</button><button className="button button-primary" onClick={saveInvoice}>Save draft invoice <ArrowRight size={15} /></button></div></> : <><label className="field-label">Description<input placeholder="e.g. Office supplies" /></label><div className="field-row"><label className="field-label">Amount (KSh)<input type="number" placeholder="0.00" /></label><label className="field-label">Type<select defaultValue="Expense"><option>Expense</option><option>Income</option><option>Transfer</option></select></label></div><label className="field-label">Account<select defaultValue="M-Pesa Till"><option>M-Pesa Till</option><option>KCB Business Account</option><option>Petty cash</option></select></label><div className="dialog-actions"><button className="button button-secondary" onClick={() => setModal(null)}>Cancel</button><button className="button button-primary" onClick={() => { setModal(null); notify('Transaction added to your books') }}>Add transaction <ArrowRight size={15} /></button></div></>}</div></div>}
    {toast && <div className="toast"><span><Check size={15} /></span>{toast}<button aria-label="Dismiss notification" onClick={() => setToast('')}><X size={14} /></button></div>}
  </div>
}
export default App
